ALTER TABLE skills
ADD COLUMN IF NOT EXISTS scope TEXT NOT NULL DEFAULT 'personal';

ALTER TABLE tools
ADD COLUMN IF NOT EXISTS scope TEXT NOT NULL DEFAULT 'personal';

CREATE TABLE IF NOT EXISTS user_skill_installs (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, skill_id)
);

CREATE TABLE IF NOT EXISTS user_tool_installs (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tool_id TEXT NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, tool_id)
);

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS model TEXT NOT NULL DEFAULT '';

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS reasoning TEXT NOT NULL DEFAULT '';
